In [19]:
import pandas as pd
import numpy as np
import pickle
import timeit

In [3]:
with open('yelp_businesses.pickle', 'rb') as pickleReader:
    business_dict = pickle.load(pickleReader)
        

In [8]:
business_dict['JzOp695tclcNCNMuBl7oxA']['coordinates']['latitude']

{'latitude': 33.419568, 'longitude': -111.916097}

In [9]:
business_dict['JzOp695tclcNCNMuBl7oxA']['coordinates']['latitude']

33.419568

In [10]:
business_dict['JzOp695tclcNCNMuBl7oxA']['coordinates']['longitude']

-111.916097

In [65]:
locations = np.zeros((len(business_dict),2))

for ix, k in enumerate(business_dict.keys()):
    locations[ix,0] = business_dict[k]['coordinates']['latitude']
    locations[ix,1] = business_dict[k]['coordinates']['longitude']


In [94]:
locations = locations[~np.isnan(locations[:,0])]

array([[  33.419568  , -111.916097  ],
       [  33.4143486 , -111.91303253],
       [  33.407997  , -111.887898  ],
       [  33.4068413 , -111.9075394 ],
       [  33.3937812 , -111.9085823 ],
       [  33.40625446, -111.90948013],
       [  33.40710155, -111.90966843],
       [  33.4276    , -111.89997   ],
       [  33.41434   , -111.9127    ],
       [  33.415079  , -111.905095  ],
       [  33.394965  , -111.909476  ],
       [  33.41315   , -111.87577   ],
       [  33.421413  , -111.914915  ],
       [  33.4140838 , -111.8722964 ],
       [  33.394724  , -111.875314  ],
       [  33.3946117 , -111.9089851 ],
       [  33.394049  , -111.872942  ],
       [  33.3765345 , -111.8778341 ],
       [  33.3946117 , -111.9089851 ],
       [  33.39174   , -111.90839   ]])

In [60]:
locations = locations[~np.isnan(locations)]

In [57]:
pd.read_csv?

In [46]:
nn = np.ones((len(business_dict),1))

In [ ]:
for ix, r in enumerate(locations):
    for cycle in locations:
        if set(r) != set(cycle):
            dist = euclidean_distances([r], [cycle])
            if nn[ix] > dist:
                nn[ix] = dist

for n in nn:
    print(n)

In [62]:
locations

array([  33.419568 , -111.916097 ,   33.4143486, ..., -118.4150314,
         33.334357 , -118.310858 ])

In [29]:
from sklearn.metrics.pairwise import euclidean_distances
X = [[0, 1], [1, 1]]
# distance between rows of X
euclidean_distances(X, X)


array([[0., 1.],
       [1., 0.]])